Numpy常见用法

In [1]:
import numpy as np

## 一、打乱随机矩阵

### 生成矩阵

In [2]:
a=np.arange(16)
b=a.reshape(4,-1)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

### 生成随机排列序列

In [3]:
c=np.random.permutation(np.arange(4))
c

array([1, 0, 3, 2])

### 应用到矩阵索引上

In [4]:
b[c]

array([[ 4,  5,  6,  7],
       [ 0,  1,  2,  3],
       [12, 13, 14, 15],
       [ 8,  9, 10, 11]])

## 二、zip组合矩阵

In [14]:
a=[1,2,3]
b=[4,5,6]
zz=zip(a,b)
for k in zz:
    print(k)

(1, 4)
(2, 5)
(3, 6)
